### ISSUE TITLE
Is there any published article describing SP-UMP2?

### ISSUE THREAD

**Issue by hebrewsnabla** [shufay/SP-UMP2#1]
This repo looks very interesting for me. Is there any published article describing SP-UMP2? It looks a little bit like Tsuchimochi's SUPT2 but the projected UHF orbital is not optimized, I guess.

**Comment by shufay** [comment]
Hi, thank you for your interest in my repo! SP-UMP2 is currently in development. Indeed, it is similar to SUPT2--the difference is that SUPT2 is a variation-after-projection method while SP-UMP2 is a projection-after-variation method. It is most similar to this paper by Schlegel (https://pubs.acs.org/doi/abs/10.1021/j100322a014), with the spin-projector implemented using a series of rotations.

**Comment by hebrewsnabla** [comment]
OK, thank you very much.
