### ISSUE TITLE
no 'process_clock' in old pyscf.lib.logger

### ISSUE THREAD

**Issue by hebrewsnabla** [shufay/SP-UMP2#3]
I found an error when executing an example of opt_spump2, with shufay/pyscf's dfgmp2 branch
```
  File "/share/home/srwang/SP-UMP2/opt_spump2/dfsppt2.py", line 1221, in _make_eris_incore
    cput0 = (logger.process_clock(), logger.perf_counter())
AttributeError: module 'pyscf.lib.logger' has no attribute 'process_clock'
```
I think process_clock was introduced in pyscf 2.0.0 (https://github.com/pyscf/pyscf/commit/6d9a322bbcd1145ecdbfa0240cc0ab8f1c34c410#diff-f4019f0858f37cf5757e341b2821745a131fd2af209f4e628f9d0f8d81c8fe9a), but dfgmp2 branch stays at 1.7.
Maybe you have pulled that in your local repo, but shufay/pyscf is not updated?

**Comment by shufay** [comment]
You are correct--thanks for letting me know! The version of pyscf the code uses is the master branch here: https://github.com/pyscf/pyscf. I'll update the description in the README.
